[package]
name = "er-save-file-readers"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde-wasm-bindgen = "0.4"
serde = { version = "1.0", features = ["derive"] }
byteorder = "1"

[lib]
crate-type = ["cdylib", "rlib"]