name: Build and Deploy Rust WASM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build with wasm-pack
        run: |
          wasm-pack build --target web

      - name: Upload WASM artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wasm-artifacts
          path: rust/er-save-file-readers/pkg/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download WASM artifacts
        uses: actions/download-artifact@v2
        with:
          name: wasm-artifacts

      # Add your deployment steps here
      # This can be deploying to Vercel, Netlify, or any other service
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel --prod --confirm
